export const students = [
  {
    id: 1,
    name: "Yashpreet Singh",
    instituteId: "2200259",
    department: "CSE",
    email: "yashpreet.singh@example.com",
    resume: "resume_yashpreet.pdf",
    cgpa: 8.5,
    skills: "Full Stack Dev",
  },
  {
    id: 2,
    name: "Aarav Mehta",
    instituteId: "2200260",
    department: "ECE",
    email: "aarav.mehta@example.com",
    resume: "resume_aarav.pdf",
    cgpa: 8.2,
    skills: "Embedded Systems",
  },
  {
    id: 3,
    name: "Isha Sharma",
    instituteId: "2200261",
    department: "CSE",
    email: "isha.sharma@example.com",
    resume: "resume_isha.pdf",
    cgpa: 9.1,
    skills: "UI/UX, ReactJS",
  },
  {
    id: 4,
    name: "Rohan Verma",
    instituteId: "2200262",
    department: "ME",
    email: "rohan.verma@example.com",
    resume: "resume_rohan.pdf",
    cgpa: 7.8,
    skills: "AutoCAD, SolidWorks",
  },
  {
    id: 5,
    name: "Simran Kaur",
    instituteId: "2200263",
    department: "CSE",
    email: "simran.kaur@example.com",
    resume: "resume_simran.pdf",
    cgpa: 9.0,
    skills: "Machine Learning, Python",
  },
  {
    id: 6,
    name: "Aditya Joshi",
    instituteId: "2200264",
    department: "IT",
    email: "aditya.joshi@example.com",
    resume: "resume_aditya.pdf",
    cgpa: 8.3,
    skills: "Cloud Computing, AWS",
  },
  {
    id: 7,
    name: "Neha Bansal",
    instituteId: "2200265",
    department: "ECE",
    email: "neha.bansal@example.com",
    resume: "resume_neha.pdf",
    cgpa: 8.7,
    skills: "VLSI Design",
  },
  {
    id: 8,
    name: "Karan Malhotra",
    instituteId: "2200266",
    department: "CSE",
    email: "karan.malhotra@example.com",
    resume: "resume_karan.pdf",
    cgpa: 7.9,
    skills: "Backend Dev, Node.js",
  },
  {
    id: 9,
    name: "Riya Kapoor",
    instituteId: "2200267",
    department: "IT",
    email: "riya.kapoor@example.com",
    resume: "resume_riya.pdf",
    cgpa: 9.2,
    skills: "Cybersecurity, Linux",
  },
  {
    id: 10,
    name: "Manav Gupta",
    instituteId: "2200268",
    department: "CSE",
    email: "manav.gupta@example.com",
    resume: "resume_manav.pdf",
    cgpa: 8.0,
    skills: "Data Science, Pandas",
  },
  {
    id: 11,
    name: "Sneha Rathi",
    instituteId: "2200269",
    department: "EE",
    email: "sneha.rathi@example.com",
    resume: "resume_sneha.pdf",
    cgpa: 8.6,
    skills: "Power Systems",
  },
  {
    id: 12,
    name: "Tanishq Agarwal",
    instituteId: "2200270",
    department: "CSE",
    email: "tanishq.agarwal@example.com",
    resume: "resume_tanishq.pdf",
    cgpa: 8.1,
    skills: "Java, DSA",
  },
  {
    id: 13,
    name: "Pooja Sinha",
    instituteId: "2200271",
    department: "IT",
    email: "pooja.sinha@example.com",
    resume: "resume_pooja.pdf",
    cgpa: 9.3,
    skills: "DevOps, Docker",
  },
  {
    id: 14,
    name: "Nikhil Tiwari",
    instituteId: "2200272",
    department: "ME",
    email: "nikhil.tiwari@example.com",
    resume: "resume_nikhil.pdf",
    cgpa: 7.5,
    skills: "CAM, ANSYS",
  },
  {
    id: 15,
    name: "Aditi Chauhan",
    instituteId: "2200273",
    department: "CSE",
    email: "aditi.chauhan@example.com",
    resume: "resume_aditi.pdf",
    cgpa: 8.9,
    skills: "Web Dev, Next.js",
  },
  {
    id: 16,
    name: "Rahul Das",
    instituteId: "2200274",
    department: "EEE",
    email: "rahul.das@example.com",
    resume: "resume_rahul.pdf",
    cgpa: 7.6,
    skills: "IoT, Arduino",
  },
  {
    id: 17,
    name: "Mira Khan",
    instituteId: "2200275",
    department: "CSE",
    email: "mira.khan@example.com",
    resume: "resume_mira.pdf",
    cgpa: 9.4,
    skills: "AI, NLP",
  },
  {
    id: 18,
    name: "Varun Sethi",
    instituteId: "2200276",
    department: "IT",
    email: "varun.sethi@example.com",
    resume: "resume_varun.pdf",
    cgpa: 8.2,
    skills: "Mobile Dev, Flutter",
  },
  {
    id: 19,
    name: "Priya Desai",
    instituteId: "2200277",
    department: "ECE",
    email: "priya.desai@example.com",
    resume: "resume_priya.pdf",
    cgpa: 9.0,
    skills: "Signal Processing",
  },
  {
    id: 20,
    name: "Harshit Jain",
    instituteId: "2200278",
    department: "CSE",
    email: "harshit.jain@example.com",
    resume: "resume_harshit.pdf",
    cgpa: 8.4,
    skills: "Blockchain, Solidity",
  },
];
